In [1]:
import pandas as pd
import numpy as np

In [2]:
# pd. Series(집합적 자료형)
# pd. Series(리스트)
s = pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [3]:
# pd. Series(튜플)
s = pd.Series((1.0,2.0,3.0))
s

0    1.0
1    2.0
2    3.0
dtype: float64

In [4]:
# pd. Series(1,2,3) 집합적 자료형 이용해야함

In [5]:
s2 = pd.Series(['a','a','c'])  # dtype: object
s2

0    a
1    a
2    c
dtype: object

In [6]:
s2 = pd.Series(['a',1, 3.0])  # dtype: object
s2

0      a
1      1
2    3.0
dtype: object

In [7]:
s = pd.Series(range(10,14))
s

0    10
1    11
2    12
3    13
dtype: int64

In [8]:
range(10,14)

range(10, 14)

In [9]:
np.arange(10,14)

array([10, 11, 12, 13])

In [10]:
np.arange(200)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [11]:
s = pd.Series(np.arange(200))
s

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

In [12]:
# NaN은 np.nan 속성을 이용해서 생성
s = pd.Series([1,2,3,np.nan,6,8])
s
# dtype = float64

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
# 인덱스 명시해서 시리즈 만들기

In [15]:
s0 = pd.Series([10,20,30], index=[1,2,3])
s0

1    10
2    20
3    30
dtype: int64

In [14]:
s = pd.Series([95,100,88], index=['홍길동','이몽룡','성춘향'])
s

홍길동     95
이몽룡    100
성춘향     88
dtype: int64

In [16]:
# 시리즈의 index
s0.index

Int64Index([1, 2, 3], dtype='int64')

In [17]:
s00 = pd.Series([1,2,3])  # index 명시하지 않음
s00.index

RangeIndex(start=0, stop=3, step=1)

In [19]:
s = pd.Series([99999, 88888, 77777, 66666], index=['서울', '부산', '인천', '대구'])
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [21]:
# 시리즈의 index.name 속성
s.index.name = '광역시'
s

광역시
서울    99999
부산    88888
인천    77777
대구    66666
dtype: int64

In [22]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')

In [23]:
s.values  # 시리즈 값의 전체 형태는 array 형태

array([99999, 88888, 77777, 66666], dtype=int64)

In [24]:
# 시리즈.name 속성
s.name = '인구'
s

광역시
서울    99999
부산    88888
인천    77777
대구    66666
Name: 인구, dtype: int64

In [25]:
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


### 인덱싱

- 원소접근(문자형, 정수형)

In [26]:
s['인천']

77777

In [27]:
s[2]

77777

In [29]:
s03 = pd.Series([1,2,3], index=[1,2,3])
s03

1    1
2    2
3    3
dtype: int64

In [30]:
s03[1]

1

In [31]:
s['부산']

88888

In [32]:
s[3], s['대구']

(66666, 66666)

- 리스트 이용 인덱싱

In [33]:
s[0],s[3],s[1]

(99999, 66666, 88888)

In [34]:
s[[0, 3, 1]]

광역시
서울    99999
대구    66666
부산    88888
Name: 인구, dtype: int64

- 시리즈 슬라이싱

In [35]:
s[1:3]

광역시
부산    88888
인천    77777
Name: 인구, dtype: int64

In [36]:
s['부산':'대구']

광역시
부산    88888
인천    77777
대구    66666
Name: 인구, dtype: int64

In [37]:
# 정수형 인덱스 명시가 안 좋은 이유(문자형으로 명시 권장)
s1 = pd.Series([100,200,300,400], index=[1,2,3,4])
s1[[2,3,4]]

2    200
3    300
4    400
dtype: int64

In [38]:
# 슬라이싱은 0-base 슬라이싱
s1[2:4]

3    300
4    400
dtype: int64

- 인덱스 재사용하기

In [39]:
s1 = pd.Series(np.arange(4), s.index)
s1

광역시
서울    0
부산    1
인천    2
대구    3
dtype: int32

### 시리즈 연산

- 벡터화 연산(numpy배열 처럼 시리즈도 가능): 집합적 자료형 원소 각각을 독립적으로 계산을 진행하는 방법

In [40]:
pd.Series([1,2,3]) + 4

0    5
1    6
2    7
dtype: int64

In [41]:
s[(s>250e4) & (s<500e4)]

Series([], Name: 인구, dtype: int64)

In [42]:
# Boolean Selection
s0 = pd.Series(np.arange(10), np.arange(10)+1)
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [43]:
s0 > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [44]:
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int32

In [45]:
s0[s0%2 == 0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [46]:
s0.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
s0[s0.index > 5]

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [48]:
s0[(s0>5)&(s0<8)]

7    6
8    7
dtype: int32

In [49]:
(s0>=7).sum() # True의 개수 총 합

3

In [50]:
(s0[s0>=7]).sum() # 조건의 결과가 True인 원소들의 합

24

In [51]:
num_s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])
num_s1

a    1
b    2
c    3
d    4
dtype: int64

In [52]:
num_s2 = pd.Series([5,6,7,8], index=['b','c','d','a'])
num_s2

b    5
c    6
d    7
a    8
dtype: int64

In [53]:
num_s1 + num_s2 # 같은 인덱스 찾아 연산 진행

a     9
b     7
c     9
d    11
dtype: int64

In [56]:
num_s3 = pd.Series([5,6,7,8], index=['e','b','f','g'])
num_s4 = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [57]:
num_s3 - num_s4  # 동일한 인덱스만 연산 진행

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [58]:
num_s3.values - num_s4.values

array([4, 4, 4, 4], dtype=int64)

### 딕셔너리와 시리즈

- 시리즈는 라벨에 의해 인덱싱 가능
- 라벨을 key로 가지는 딕셔너리 형과 같음
- 딕셔너리에서 제공하는 대부분의 연산자 사용 가능(`in`연산자, `for`루프)

In [59]:
s

광역시
서울    99999
부산    88888
인천    77777
대구    66666
Name: 인구, dtype: int64

In [60]:
'서울' in s

True

In [61]:
'대전' in s

False

In [62]:
'대전' not in s

True

In [63]:
s.items()

In [64]:
list(s.items())

[('서울', 99999), ('부산', 88888), ('인천', 77777), ('대구', 66666)]

In [66]:
for k, v in s.items():
    print('%s=%d' % (k,v))

서울=99999
부산=88888
인천=77777
대구=66666


### 딕셔너리로 시리즈 만들기
- `Series({key:value, key:value, ...})`
- index -> key
- 값 -> value

In [68]:
scores={'홍길동':96, '이몽룡': 100, '성춘향':88}
s = pd.Series(scores)
s

홍길동     96
이몽룡    100
성춘향     88
dtype: int64

In [69]:
city = {'서울': 9631482, '부산':3393191, '인천':2632035, '대전':1490158}
s = pd.Series(city, index=city.keys())
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [70]:
s = pd.Series(city, index=['부산', '인천', '서울', '대전'])
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

### 시리즈 데이터의 갱신, 추가, 삭제

In [71]:
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [72]:
s['부산'] = 1630000
s

부산    1630000
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [73]:
del s['서울']
s

부산    1630000
인천    2632035
대전    1490158
dtype: int64

### Series 함수
- `size`(속성): 개수
- `shape`(속성): 튜플 형태로 shape 반환
- `unique`: 유일한 값만 ndarray로 반환
- `count`: NaN을 제외한 개수 반환
- `mean`: NaN을 제외한 평균
- `value_counts`: NaN을 제외하고 각 값들의 빈도를 반환

In [74]:
s1 = pd.Series([1,1,2,1,2,2,2,1,1,3,3,4,5,5,7,np.NaN])
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [75]:
len(s1)

16

In [76]:
s1.size

16

In [77]:
s1.shape

(16,)

In [79]:
s1.unique()  # nan도 하나의 값으로 봄

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [80]:
s1.count()  # nan제외

15

In [81]:
a = np.array([2,2,2,2,np.NaN]) # array 타입
a.mean()

nan

In [83]:
b = pd.Series(a)
b.mean()

2.0

In [84]:
s1.value_counts()

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
dtype: int64

### 날짜 자동 생성: date_range

In [85]:
index_date = ['2018-10-07', '2018-10-08', '2018-10-09', '2018-10-10']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [86]:
type(s4.index[0])

str

- pandas 패키지의 `date_range` 함수(날짜 생성)
    - `pd.date_range(start=None, end=None, periods=None, freq='D')`
    - `start`: 시작 날짜, `end`: 끝 날짜, `periods`: 날짜 생성기간, `freq`: 날짜 생성 주기

In [87]:
pd.date_range(start='2018-10-01', end='2018-10-20')

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [89]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq = '3D')

DatetimeIndex(['2018-10-01', '2018-10-04', '2018-10-07', '2018-10-10',
               '2018-10-13', '2018-10-16', '2018-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [90]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq = 'w')

DatetimeIndex(['2018-10-07', '2018-10-14'], dtype='datetime64[ns]', freq='W-SUN')

In [91]:
pd.date_range(start='2018-10-01', periods=4, freq = 'w')

DatetimeIndex(['2018-10-07', '2018-10-14', '2018-10-21', '2018-10-28'], dtype='datetime64[ns]', freq='W-SUN')

In [92]:
pd.date_range(start='2018-10-01', periods=4, freq = 'm')

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='M')

In [93]:
pd.date_range(start='2018-10-01', periods=4, freq = 'MS')

DatetimeIndex(['2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01'], dtype='datetime64[ns]', freq='MS')

In [94]:
pd.date_range(start='2018-10-01', periods=12, freq = '2BM')  # 업무일 기준 2개월 간격 월말 주기

DatetimeIndex(['2018-10-31', '2018-12-31', '2019-02-28', '2019-04-30',
               '2019-06-28', '2019-08-30', '2019-10-31', '2019-12-31',
               '2020-02-28', '2020-04-30', '2020-06-30', '2020-08-31'],
              dtype='datetime64[ns]', freq='2BM')

In [95]:
pd.date_range(start='2018-10-01', periods=4, freq = 'QS') # 분기 시작일 기준

DatetimeIndex(['2018-10-01', '2019-01-01', '2019-04-01', '2019-07-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [96]:
pd.date_range(start='2018-10-01', periods=4, freq = 'AS') # 연도 시작일 기준

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [97]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq = 'H')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 09:00:00',
               '2018-01-20 10:00:00', '2018-01-20 11:00:00',
               '2018-01-20 12:00:00', '2018-01-20 13:00:00',
               '2018-01-20 14:00:00', '2018-01-20 15:00:00',
               '2018-01-20 16:00:00', '2018-01-20 17:00:00'],
              dtype='datetime64[ns]', freq='H')

In [98]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq = 'BH') # 업무시간 기준 9 to 5 

DatetimeIndex(['2018-01-22 09:00:00', '2018-01-22 10:00:00',
               '2018-01-22 11:00:00', '2018-01-22 12:00:00',
               '2018-01-22 13:00:00', '2018-01-22 14:00:00',
               '2018-01-22 15:00:00', '2018-01-22 16:00:00',
               '2018-01-23 09:00:00', '2018-01-23 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [99]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq = '30min')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:30:00',
               '2018-01-20 09:00:00', '2018-01-20 09:30:00',
               '2018-01-20 10:00:00', '2018-01-20 10:30:00',
               '2018-01-20 11:00:00', '2018-01-20 11:30:00',
               '2018-01-20 12:00:00', '2018-01-20 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [100]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq = '10S')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:00:10',
               '2018-01-20 08:00:20', '2018-01-20 08:00:30',
               '2018-01-20 08:00:40', '2018-01-20 08:00:50',
               '2018-01-20 08:01:00', '2018-01-20 08:01:10',
               '2018-01-20 08:01:20', '2018-01-20 08:01:30'],
              dtype='datetime64[ns]', freq='10S')