In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all" # all/last/last_expr(기본값)/none
# 설정변경코드: 변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것

In [2]:
import pandas as pd
import numpy as np

## pandas 데이터처리 및 변환 관련 함수

### 데이터 개수 세기
- `count()`
    - NaN 값은 세지 않음

In [3]:
# 시리즈에서 개수 세기
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [4]:
s.count()

9

### 난수 발생시켜 dataframe 생성
- 난수 `seed(값)`라는 함수 사용 가능
- seed의 의미: 난수 알고리즘에서 사용하는 기본 값으로 시드 값이 같으면 동일한 난수 발생
- 계속 변경되는 난수 받고 싶으면 `Time.time()`

In [5]:
np.random.randint(5)
np.random.randint(5, size=4)

1

array([2, 2, 4, 0])

In [6]:
np.random.seed(3)
np.random.randint(5, size=4)  # 값 고정됨

array([2, 0, 1, 3])

In [7]:
np.random.randint(5, size=4)  # seed 리셋됨

array([0, 0, 0, 3])

In [8]:
# 시드값 매번 다르게 전달되도록 코드 작성
import time
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([1, 4, 4, 3])

In [9]:
np.random.randint(5, size=(4,4))

array([[2, 3, 0, 4],
       [1, 4, 3, 3],
       [4, 1, 4, 3],
       [0, 1, 4, 0]])

In [10]:
np.random.seed(3)
df1 = pd.DataFrame(np.random.randint(5, size=(4,4)))
df1.iloc[2,3]=np.nan
df1

,0,1,2,3
0,2,0,1,3.0
1,0,0,0,3.0
2,2,3,1,NaN
3,2,0,4,4.0


In [11]:
df1.count()  # 각열에 대한 원소의 개수 반환

0    4
1    4
2    4
3    3
dtype: int64

In [12]:
import seaborn as sns  # 그래프 패키지

In [13]:
titanic = pd.read_csv('./data/test.csv')
del titanic['Unnamed: 0']
titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False


In [14]:
titanic.tail(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [15]:
titanic.to_csv('./data/test.csv')

In [16]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

### 카테고리 값 세기
- 시리즈 값이 정수, 문자열 등 카테고리 값인 경우에 `시리즈.value_counts()` 메서드를 사용해 각각의 값이 나온 횟수를 셀 수 있음
- `normalize=True`를 사용하면 각 값 및 범주형 데이터의 비율을 계산

In [17]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size=100))
len(s2)

100

In [18]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [19]:
s2.value_counts(normalize=True)

1    0.22
0    0.18
4    0.17
5    0.16
3    0.14
2    0.13
dtype: float64

#### 범주형 데이터에 value_counts() 함수 적용
- 범주형 데이터: 관측 결과가 몇개의 범주 또는 항목의 형태로 나타나는 자료

In [20]:
# 생존 여부 yes/no로 표시되어 있음
titanic['alive'].dtype

dtype('O')

In [21]:
titanic['alive'].value_counts()

no     549
yes    342
Name: alive, dtype: int64

In [22]:
titanic['alive'].value_counts(normalize=True)

no     0.616162
yes    0.383838
Name: alive, dtype: float64

In [23]:
titanic['alive'].value_counts(normalize=True) * 100

no     61.616162
yes    38.383838
Name: alive, dtype: float64

In [24]:
# 남녀 비율
titanic['sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [25]:
titanic['sex'].value_counts(normalize=True) * 100

male      64.758698
female    35.241302
Name: sex, dtype: float64

In [26]:
titanic[['sex','alive']].head(2)

,sex,alive
0,male,no
1,female,yes


In [27]:
titanic[['sex','alive']].value_counts()

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
dtype: int64

In [28]:
type(titanic[['sex','alive']].value_counts())

pandas.core.series.Series

In [29]:
pd.DataFrame(titanic[['sex','alive']].value_counts())

,,0
sex,alive,
male,no,468
female,yes,233
male,yes,109
female,no,81


### 정렬함수
- `sort_index(ascending=True/False)`: 인덱스 기준
- `sort_value(ascending=True/False)`: 데이터 값 기준

#### 시리즈 함수

In [30]:
s2

0     5
1     3
2     4
3     0
4     1
     ..
95    4
96    5
97    2
98    4
99    3
Length: 100, dtype: int32

In [31]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [32]:
s2.value_counts().sort_index()

0    18
1    22
2    13
3    14
4    17
5    16
dtype: int64

In [33]:
s2.value_counts().sort_index(ascending=False)

5    16
4    17
3    14
2    13
1    22
0    18
dtype: int64

In [34]:
s2.value_counts().sort_values()

2    13
3    14
5    16
4    17
0    18
1    22
dtype: int64

In [35]:
s2.value_counts().sort_values(ascending=False)

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [36]:
df1

,0,1,2,3
0,2,0,1,3.0
1,0,0,0,3.0
2,2,3,1,NaN
3,2,0,4,4.0


#### 데이터프레임 정렬

In [37]:
# df1.sort_values() TypeError by

In [38]:
df1.sort_values(by=0)

,0,1,2,3
1,0,0,0,3.0
0,2,0,1,3.0
2,2,3,1,NaN
3,2,0,4,4.0


In [39]:
df1.sort_values(by=0, ascending=False)

,0,1,2,3
0,2,0,1,3.0
2,2,3,1,NaN
3,2,0,4,4.0
1,0,0,0,3.0


In [40]:
df = pd.DataFrame({'num_legs':[2,4,4,6],
                  'num_wings':[2,0,0,0]},
                 index=['falcon','dog','cat','ant'])
df

,num_legs,num_wings
falcon,2,2
dog,4,0
cat,4,0
ant,6,0


In [41]:
df.sort_index()

,num_legs,num_wings
ant,6,0
cat,4,0
dog,4,0
falcon,2,2


In [42]:
df.sort_index(ascending=False)

,num_legs,num_wings
falcon,2,2
dog,4,0
cat,4,0
ant,6,0


### 행/열 합계
- `df.sum()`
- 열의 합계: `sum(axis=0)`
- 행의 합계: `sum(axis=1)`

In [43]:
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df2

,0,1,2,3,4,5,6,7
0,5,8,9,5,0,0,1,7
1,6,9,2,4,5,2,4,2
2,4,7,7,9,1,7,0,6
3,9,9,7,6,9,1,0,1


In [44]:
# 각 행의 합계
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [45]:
# 긱 열의 합계
df2.sum(axis=0)

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [46]:
# axis 인수 생략하면 기본값이 0(각 열의 합계)
df2.sum()

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [47]:
df2['total'] = df2[[0,1,2,3,4,5,6,7]].sum(axis=1)
df2

,0,1,2,3,4,5,6,7,total
0,5,8,9,5,0,0,1,7,35
1,6,9,2,4,5,2,4,2,34
2,4,7,7,9,1,7,0,6,41
3,9,9,7,6,9,1,0,1,42


#### df의 기본 함수
- `mean()`
- `min()`
- `max()`

In [48]:
# 긱 열의 평균
df2.mean(axis=0)

0         6.00
1         8.25
2         6.25
3         6.00
4         3.75
5         2.50
6         1.25
7         4.00
total    38.00
dtype: float64

In [49]:
# 각 행의 평균
df2.mean(axis=1)

0    7.777778
1    7.555556
2    9.111111
3    9.333333
dtype: float64

In [50]:
# 긱 열의 최소값
df2.min(axis=0)

0         4
1         7
2         2
3         4
4         0
5         0
6         0
7         1
total    34
dtype: int64

In [51]:
# 긱 행의 최소값
df2.min(axis=1)

0    0
1    2
2    0
3    0
dtype: int64

In [52]:
# 긱 열의 최대값
df2.max(axis=0)

0         9
1         9
2         9
3         9
4         9
5         7
6         4
7         7
total    42
dtype: int64

In [53]:
# 긱 행의 최대값
df2.max(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [54]:
df2.loc['max_data'] = df2[[0,1,2,3,4,5,6,7]].max(axis=0)

In [55]:
df2

,0,1,2,3,4,5,6,7,total
0,5.0,8.0,9.0,5.0,0.0,0.0,1.0,7.0,35.0
1,6.0,9.0,2.0,4.0,5.0,2.0,4.0,2.0,34.0
2,4.0,7.0,7.0,9.0,1.0,7.0,0.0,6.0,41.0
3,9.0,9.0,7.0,6.0,9.0,1.0,0.0,1.0,42.0
max_data,9.0,9.0,9.0,9.0,9.0,7.0,4.0,7.0,NaN


### 행/열 삭제 - drop()
- `df.drop('row', 0)`: 행 삭제
- `df.drop('column', 1)`: 열 삭제

In [57]:
df2.drop('total',1,inplace=True)
df2

C:\Users\Administrator\AppData\Local\Temp\ipykernel_2108\2813679957.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2.drop('total',1,inplace=True)


,0,1,2,3,4,5,6,7
0,5.0,8.0,9.0,5.0,0.0,0.0,1.0,7.0
1,6.0,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,4.0,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [58]:
df2.drop('max_data',0)
df2

C:\Users\Administrator\AppData\Local\Temp\ipykernel_2108\3542995378.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df2.drop('max_data',0)


,0,1,2,3,4,5,6,7
0,5.0,8.0,9.0,5.0,0.0,0.0,1.0,7.0
1,6.0,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,4.0,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,9.0,7.0,6.0,9.0,1.0,0.0,1.0


,0,1,2,3,4,5,6,7
0,5.0,8.0,9.0,5.0,0.0,0.0,1.0,7.0
1,6.0,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,4.0,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,9.0,7.0,4.0,7.0


#### NaN값 처리 함수
- `df.dropna(axis=0/1)`
- `df.fillna(0)`

In [59]:
df2.iloc[0,0] = np.nan
df2

,0,1,2,3,4,5,6,7
0,NaN,8.0,9.0,5.0,0.0,0.0,1.0,7.0
1,6.0,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,4.0,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [60]:
df2.dropna(axis=1, inplace=True)
df2

,1,2,3,4,5,6,7
0,8.0,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [61]:
df2.iloc[0,0] = np.nan
df2

,1,2,3,4,5,6,7
0,NaN,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [62]:
df2.fillna(0)
df2

,1,2,3,4,5,6,7
0,0.0,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


,1,2,3,4,5,6,7
0,NaN,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [63]:
df2.fillna(1, inplace=True)
df2

,1,2,3,4,5,6,7
0,1.0,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


### 데이터프레임의 형변환
- `df.astype(자료형)`
- 전체 데이터에 대해서 형변환을 진행

In [64]:
df2.iloc[0,0] = np.nan
df2

,1,2,3,4,5,6,7
0,NaN,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [65]:
df2.fillna(0).astype(int)

,1,2,3,4,5,6,7
0,0,9,5,0,0,1,7
1,9,2,4,5,2,4,2
2,7,7,9,1,7,0,6
3,9,7,6,9,1,0,1
max_data,9,9,9,9,7,4,7


In [66]:
df2.fillna(0).astype(float)

,1,2,3,4,5,6,7
0,0.0,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [67]:
df2.fillna(0)[1].astype(int)  # 첫번째 열 형 변환

0           0
1           9
2           7
3           9
max_data    9
Name: 1, dtype: int32

In [68]:
test_df = df2.fillna(0).astype(float)
test_df

,1,2,3,4,5,6,7
0,0.0,9.0,5.0,0.0,0.0,1.0,7.0
1,9.0,2.0,4.0,5.0,2.0,4.0,2.0
2,7.0,7.0,9.0,1.0,7.0,0.0,6.0
3,9.0,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9.0,9.0,9.0,9.0,7.0,4.0,7.0


In [69]:
test_df[1] = test_df[1].astype(int)
test_df

,1,2,3,4,5,6,7
0,0,9.0,5.0,0.0,0.0,1.0,7.0
1,9,2.0,4.0,5.0,2.0,4.0,2.0
2,7,7.0,9.0,1.0,7.0,0.0,6.0
3,9,7.0,6.0,9.0,1.0,0.0,1.0
max_data,9,9.0,9.0,9.0,7.0,4.0,7.0


### 열 또는 행에 동일한 연산 반복 적용: apply() 함수
- `apply()` 함수는 데이터프레임의 행이나 열에 복잡한 연산을 vectorizing 할 수 있게 해주는 함수로 매우 많이 활용되는 함수
- 동일한 연산을 모든열에 혹은 모든 행에 반복 적용하고자 할 때 사용
- `apply(반복적용할 함수, axis=0/1)`
    - 0: 열마다 반복
    - 1: 행마다 반복
    - 생략시 기본값:0

In [70]:
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [71]:
np.sum([1,2,3])  # np.sum() 함수는 전달된 첫번째 인수 데이터들의 합산 결과를 반환함

6

In [72]:
np.sum(df3['a'])

15

In [73]:
np.sum(df3['b'])

15

In [74]:
np.sum(df3['c'])

16

In [75]:
for i in ['a','b','c']:
    print(np.sum(df3[i]))

15
15
16


In [76]:
df3.apply(np.sum, 0)  # for문 쓴 거랑 같은 결과

a    15
b    15
c    16
dtype: int64

In [77]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [78]:
titanic[['alive','sex','class']].apply(pd.value_counts, 0)

,alive,sex,class
First,NaN,NaN,216.0
Second,NaN,NaN,184.0
Third,NaN,NaN,491.0
female,NaN,314.0,NaN
male,NaN,577.0,NaN
no,549.0,NaN,NaN
yes,342.0,NaN,NaN


- 데이터프레임의 기본 집계함수(`sum`, `min`, `max`, `mean` 등)들은 행/열 단위 벡터화 연산을 수행함
    - `apply()` 함수를 사용할 필요가 없음

- 일반적으로 `apply()` 함수 사용은 복잡한 연산을 해결하기 위한 `lambda` 함수나 사용자 정의 함수를 각 열 또는 행에 일괄 적용시키기 위해 사용

#### 사용자 정의 함수를 apply()에 사용하는 예제

In [79]:
def diff(x):
    return x.max() - x.min()

In [80]:
df3

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [81]:
diff(df3['a'])

3

In [82]:
diff(df3['b'])

4

In [83]:
diff(df3['c'])

4

In [84]:
df3.apply(diff, 0)

a    3
b    4
c    4
dtype: int64

In [86]:
pd.Series(3)
pd.Series(3).max()

0    3
dtype: int64

3

#### lambda 함수 apply()에 사용하는 예제

In [87]:
(lambda x:x.max()-x.min())(df3['a'])

3

In [88]:
df3.apply(lambda x:x.max()-x.min(),0)

a    3
b    4
c    4
dtype: int64

#### apply()함수 사용하지 말고 최댓값과 최솟값 차이 구하기

In [89]:
df3.max(axis=0) - df3.min(axis=0)

a    3
b    4
c    4
dtype: int64

#### np.square 함수
- `np.square` 함수는 행/열 별 각 원소에 대해 제곱승 연산을 진행하므로 행적용이나 열적용 모두 동일한 결과 나타남

In [92]:
import numpy as np
np.square([1,2,3])

array([1, 4, 9])

In [93]:
df3.apply(np.square,0)

,a,b,c
0,1,4,1
1,9,9,25
2,16,1,4
3,9,16,16
4,16,25,16


In [94]:
df3.apply(np.square,1)

,a,b,c
0,1,4,1
1,9,9,25
2,16,1,4
3,9,16,16
4,16,25,16


#### 데이터값을 카테고리 값으로 변환
- `cut(data, bins, labels)`
    - data: 구간 나눌 실제 값
    - bins: 구간 경계값
    - labels: 카테고리값
- `qcut(data, 구간수, labels)`

In [95]:
ages=[0,0.5,4,6,4,5,2,10,21,23,37,15,38,31,61,20,41,31,100]

In [96]:
# data: 구간 나눌 실제 값, bins: 구간 경계값, label: 카테고리 값
data = ages

# 구간 경계값
# 구간 최솟값 < 구간 <= 구간 최댓값
bins=[0,4,18,25,35,60,100]
# 0~4 구간: 영유아 0살 < 영유아 <= 4살

# 각 구간의 이름: labels - 카테고리명
# 순서는 구간(bins)의 순서와 동일해야 함
labels = ['영유아','미성년자','청년','중년','장년','노년']

In [97]:
len(data)

19

In [98]:
cats = pd.cut(data, bins, labels=labels)
cats

[NaN, '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청년', '장년', '중년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [99]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [100]:
cat_list = list(cats)

In [101]:
cat_list

[nan,
 '영유아',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '청년',
 '장년',
 '미성년자',
 '장년',
 '중년',
 '노년',
 '청년',
 '장년',
 '중년',
 '노년']

In [102]:
test = pd.DataFrame({'나이':ages, '연령대':cat_list})
test

,나이,연령대
0,0.0,NaN
1,0.5,영유아
2,4.0,영유아
3,6.0,미성년자
4,4.0,영유아
5,5.0,미성년자
6,2.0,영유아
7,10.0,미성년자
8,21.0,청년
9,23.0,청년


In [103]:
test['연령대'].value_counts()

영유아     4
미성년자    4
청년      3
장년      3
중년      2
노년      2
Name: 연령대, dtype: int64

### Categorical 클래스 객체
- 카테고리명 속성: `Categorical.categories`
    - 카테고리명 저장
- 코드 속성: `Categorical.codes`
    - 인코딩한 카테고리 값을 정수로 갖는다.

In [104]:
cats.categories  # cats 변수내의 범주 index를 저장

Index(['영유아', '미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [105]:
cats.codes  # 인덱스 위치 정수값이 -1이면 NaN으로 결정되어 결측치가 됨

array([-1,  0,  0,  1,  0,  1,  0,  1,  2,  2,  4,  1,  4,  3,  5,  2,  4,
        3,  5], dtype=int8)

#### 구간 경계선을 지정하지 않고 데이터 개수가 같도록 지정한 수의 구간으로 분할하기: qcut()
- 형식: `pd.qcut(data, 구간수, labels=[d1,d2, ...])`

In [106]:
# 랜덤정수 20개 생성하고 생성된 정수를 4개의 구간으로 나누기
# 각 구간의 label은 Q1, Q2, Q3, Q4

np.random.seed(2)
data = np.random.randint(20, size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

In [107]:
qcat = pd.qcut(data, 4, labels=['Q1','Q2', 'Q3', 'Q4'])
qcat

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [108]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [109]:
pd.value_counts(qcat)

Q1    5
Q2    5
Q3    5
Q4    5
dtype: int64

In [110]:
df0 = pd.DataFrame(data, columns=['관측수'])
df0['범주'] = qcat
df0

,관측수,범주
0,8,Q2
1,15,Q4
2,13,Q4
3,8,Q2
4,11,Q3
5,18,Q4
6,11,Q3
7,8,Q2
8,7,Q2
9,2,Q1


### 인덱스 설정 함수
#### 데이터프레임 인덱스 설정을 위해 set_index(), reset_index()
- `set_index()`: 기존 행 인덱스 제거하고 데이터 열 중 하나를 인덱스로 설정
- `reset_index()`: 기존 행 인덱스 제거하고 기본 인덱스로 변경
- 기본 인덱스: 0부터 1씩 증가하는 정수 인덱스

In [111]:
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [112]:
df3.set_index('a') # 원본 반영되지 않음
df3

,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [113]:
df3.set_index('a', inplace=True)
df3

,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


In [114]:
df3.loc[3]

,b,c
a,,
3,3,5
3,4,4


In [115]:
# 기본 인덱스로 인덱스 수정하기
df3.reset_index()
df3  # 원본반영안됨

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


In [116]:
# 기존 인덱스 삭제
df3.reset_index(drop=True)

,b,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


In [117]:
df3.reset_index(drop=True, inplace=True)
df3

,b,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


### index 이름 변경
- `rename(index={현재 index: 바꿀 index})`
- `rename(columns={현재 column: 바꿀 column})`

In [118]:
df3

,b,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


In [119]:
df3.rename(index={0:'1반', 1:'2반'})

,b,c
1반,2,1
2반,3,5
2,1,2
3,4,4
4,5,4


In [120]:
df3.rename(columns={'b':'학생'}, inplace=True)
df3

,학생,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


### 리스트 내포 연산
#### 리스트 내포 for문의 일반 문법

- `[표현식(연산식) for 항목 in 반복가능객체 if 조건문]`
- if 조건문 생략가능
- 반복가능객체: 리스트, 튜플, 딕셔너리, range() 등

In [122]:
a = [1,2,3,4]
result = []

for num in a:
    result.append(num*2)
result

[2, 4, 6, 8]

In [123]:
result = [num*2 for num in a]
result

[2, 4, 6, 8]

In [124]:
test = []
for i in range(1,5):
    test.append('id_'+str(i))
test

['id_1', 'id_2', 'id_3', 'id_4']

In [125]:
test = ['id_'+str(i) for i in range(1,5)]
test

['id_1', 'id_2', 'id_3', 'id_4']